# Generated by Django 4.0.1 on 2022-01-11 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cases_number', models.CharField(max_length=6)),
                ('date', models.DateField(verbose_name='date_created')),
                ('order_number', models.CharField(max_length=100)),
                ('rma_type', models.CharField(choices=[('repair', 'repair'), ('part', 'part'), ('replace', 'replace')], default='part', max_length=10)),
                ('part', models.CharField(max_length=256)),
                ('return_label', models.BooleanField()),
                ('tracking_number', models.CharField(max_length=256)),
                ('carrier', models.CharField(max_length=36)),
                ('status', models.CharField(choices=[('TS', 'Tracking Sent'), ('CA', 'Contact Agent'), ('CT', 'Check Tracking')], max_length=2)),
                ('message', models.TextField()),
                ('case_processed', models.BooleanField()),
            ],
        ),
    ]
