# Generated by Django 4.0.1 on 2022-01-11 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cases',
            new_name='Case',
        ),
    ]
