# Generated by Django 4.0.1 on 2022-01-11 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_rename_cases_number_case_case_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='id',
        ),
        migrations.AlterField(
            model_name='case',
            name='case_number',
            field=models.CharField(max_length=6, primary_key=True, serialize=False),
        ),
    ]
