# Generated by Django 4.0.1 on 2022-01-12 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0004_remove_case_id_alter_case_case_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='rma_type',
            field=models.CharField(choices=[('Repair', 'Repair'), ('Rart', 'Rart'), ('Replace', 'Replace')], default='part', max_length=10),
        ),
    ]
