# Generated by Django 4.0.1 on 2022-01-14 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0006_alter_case_rma_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repair_msg', models.TextField()),
                ('re_msg', models.TextField()),
                ('part_msg', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='case',
            name='case_creator',
            field=models.CharField(default='None', max_length=256),
        ),
        migrations.AddField(
            model_name='case',
            name='case_origin',
            field=models.CharField(default='None', max_length=265),
        ),
        migrations.AddField(
            model_name='case',
            name='repair_notes',
            field=models.TextField(default='None'),
        ),
        migrations.AlterField(
            model_name='case',
            name='message',
            field=models.TextField(default='None'),
        ),
    ]
